name: mnzk-net
channels:
  - pytorch
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.4
  - anaconda-client=1.11.3
  - anaconda-cloud-auth=0.5.1
  - anaconda-navigator=2.5.4
  - annotated-types=0.6.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - archspec=0.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - clyent=1.2.2
  - comm=0.2.1
  - conda=24.5.0
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - conda-repo-cli=1.0.41
  - conda-token=0.4.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.13.1
  - fmt=9.1.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.13.5
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.10
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - menuinst=2.0.2
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - navigator-updater=0.5.0
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - openjpeg=2.3.0
  - openssl=3.0.14
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathlib=1.0.1
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=22.3.1
  - pkce=1.0.3
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python.app=3
  - pytorch=2.3.1
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.29.0
  - requests-toolbelt=0.9.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - seaborn=0.12.2
  - semver=3.0.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.12
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - truststore=0.8.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023c
  - ujson=5.4.0
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.10
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - arviz==0.12.1
      - astunparse==1.6.3
      - branca==0.7.1
      - cachetools==5.3.1
      - cftime==1.6.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - deprecat==2.1.1
      - dill==0.3.8
      - dm-tree==0.1.8
      - download==0.3.5
      - einops==0.8.0
      - fastprogress==1.0.3
      - fiona==1.9.6
      - flatbuffers==23.5.26
      - folium==0.16.0
      - fsspec==2024.2.0
      - future==0.18.3
      - gast==0.4.0
      - geomloss==0.2.6
      - geopandas==0.14.3
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5netcdf==1.3.0
      - h5py==3.8.0
      - iprogress==0.4
      - joblib==1.2.0
      - keras==2.15.0
      - libclang==16.0.0
      - libsvmdata==0.4.1
      - lightning-utilities==0.11.2
      - lucid==0.2.3
      - markdown==3.4.3
      - matplotlib-label-lines==0.7.0
      - matplotx==0.3.10
      - ml-dtypes==0.2.0
      - more-itertools==10.2.0
      - netcdf4==1.6.5
      - networkx==3.2.1
      - numpy==1.22.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - prettytable==3.9.0
      - protobuf==4.23.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pymc3==3.11.5
      - pyopengl==3.1.7
      - pyproj==3.6.1
      - pyqt5-sip==12.11.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.8.0
      - shapely==2.0.4
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.0
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - tensorflow-macos==2.15.0
      - tensorflow-probability==0.23.0
      - termcolor==2.3.0
      - theano-pymc==1.1.2
      - threadpoolctl==3.1.0
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchmetrics==1.3.2
      - torchvision==0.17.0
      - werkzeug==2.3.5
      - wrapt==1.14.1
      - xarray==2023.12.0
      - xarray-einstats==0.6.0
      - xyzservices==2024.4.0
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'
