name: mnzk-net
channels:
  - pytorch
  - defaults
dependencies:
  - numpy
  - pytorch
  - matplotlib
  - scikit-learn
  - tqdm
  - einops
  - jupyterlab
  - ipywidgets
  - torchaudio
  - torchvision
#  - torch
  - torchmetrics
  - markdown
  - scipy

variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'
